# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
puts "🌱 Seeding..."

Resource.create(title:"Back to School Activities", subject:"Back To School", grade:2, description:"Heading back to school is such an exciting time for our students. Spend those first days back with a collection of activities that help your students get to know you and their classmates. This BUNDLE includes over 30 printable activities and 20 digital activities that are perfect for the first weeks of school.", reviews:56, image:"https://i.imgur.com/4ToHBx2.jpg")
Resource.create(title:"Spelling Activities", subject:"Phonics", grade:1, description:"This massive pack of engaging spelling sheets allow your students to complete word work in effective and engaging ways. As a teacher, you will never have to wonder what to plan for a spelling center or activity ever again!", reviews:78, image:"https://i.imgur.com/tC5X22S.jpg")
Resource.create(title:"Sight Word Sentences", subject:"Literacy", grade:1, description:"These Sight Word Sentences and Games are designed to help students build confidence with early literacy skills. A high level of support is provided. Just one sight word is added on each page", reviews:15, image:"https://i.imgur.com/6YSc7ZG.jpg")
Resource.create(title:"Addition & Subtraction Color-By-Code", subject:"Math", grade:2, description:"Practice number matching, addition, subtraction, multiplication or division with these 15 fun and engaging differentiated color-by-code worksheets for seasons and special occasions throughout the entire school year!", reviews:56, image:"https://i.imgur.com/Ayy13Lw.jpg")
Resource.create(title:"Math Game Centers", subject:"Math", grade:2, description:"Have you heard of Toothy® yet?! Toothy® task kits are highly engaging task card math games or math centers that allow students to practice math skills and answer questions in a fun, motivating way. The answers on the back of the math task cards make the activity self-paced and self-correcting.", reviews:97, image:"https://i.imgur.com/IzcR4iD.jpg")
Resource.create(title:"No-Prep Reading Intervention", subject:"Literacy", grade:1, description:"This is a no-prep reading intervention binder that is aligned to the science of reading and explicitly teaches and reinforces letter identification, letter sounds, phonemic awareness, handwriting, CVC words, blends, digraphs, nonsense words, phoneme segmentation, sentence fluency, and more!", reviews:87, image:"https://i.imgur.com/4gnbcSp.jpg")
Resource.create(title:"STEM Bins", subject:"Science", grade:3, description:"They are also a creative and developmentally appropriate form of engineering for elementary students!
 Listed materials for each STEM Bin are found in most elementary classrooms or can be borrowed from other teachers, and you may choose which materials that you feel are best for your learning environment. Additional STEM engineering tools and photos can be added to the EDITABLE STEM Bin Covers in the separate file. Inexpensive building materials for STEM Bins can be found at Dollar Tree, Walmart, or Target Dollar Spot.", reviews:56, image:"https://i.imgur.com/KHuLc12.jpg")
Resource.create(title:"Positive Affirmations:Coloring Journal", subject:"Social Emotional", grade:4, description:"This resource is intended for use by ONE classroom teacher. Permission to copy for single classroom use only. Electronic distribution limited to single classroom use only. Not for public display without credit given to author.", reviews:77, image:"https://i.imgur.com/GuFxUWz.jpg")
Resource.create(title:"2nd Grade Social Studies", subject:"Social Studies", grade:2, description:"2nd Grade Social Studies Curriculum is an engaging social studies curriculum with young learners in mind! 2nd Grade Social Studies encourages young learners to think “outside the box” and prove their thinking through hands-on and engaging learning experiences. 2nd Grade Social Studies is based upon five units: Government and Democracy, Historical Thinking, Geography, Cultures and Economics. Each unit is broken down to 10 lessons and each lesson can take from 1-2 days to complete. The units cover at least two weeks of instruction. The lesson plan has the listed objective, “I can” statement, vocabulary, detailed activity lesson plans and all necessary student follow-up practice sheets.", reviews:65, image:"https://i.imgur.com/G7WGyax.jpg")




puts "✅ Done seeding!"